spring.application.name=mywalletapp
# Server Configuration
server.port=8098

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:8085/my_wallet_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# HikariCP Configuration
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000

# JPA & Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Logging Configuration

logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Security Configuration
spring.security.user.name=${ADMIN_USERNAME:admin}
spring.security.user.password=${ADMIN_PASSWORD}

# Use a strong secret key in your production application
app.jwtSecret=${JWT_SECRET}
app.jwtExpirationMs=3600000







